"""Añadir columna cover_image_url a books

Revision ID: 1cd69fecdb03
Revises: d47497c2b47e
Create Date: 2025-04-26 09:39:45.767278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cd69fecdb03'
down_revision: Union[str, None] = 'd47497c2b47e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('cover_image_url', sa.String(length=512), nullable=True))
    op.alter_column('books', 'average_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_index('ix_books_genre', table_name='books')
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.create_index('ix_books_genre', 'books', ['genre'], unique=False)
    op.alter_column('books', 'average_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('books', 'cover_image_url')
    # ### end Alembic commands ###
