"""Add is_deleted column to reviews for soft delete

Revision ID: 3066cc73b616
Revises: c8471deb31a9
Create Date: 2025-04-27 18:27:01.019273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3066cc73b616'
down_revision: Union[str, None] = 'c8471deb31a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_reviews_is_deleted'), 'reviews', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_is_deleted'), table_name='reviews')
    op.drop_column('reviews', 'is_deleted')
    # ### end Alembic commands ###
